# Generated by Django 5.0.7 on 2024-08-18 03:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0006_alter_carinventory_cars_count_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo1', models.ImageField(blank=True, null=True, upload_to='cars/')),
                ('photo2', models.ImageField(blank=True, null=True, upload_to='cars/')),
                ('photo3', models.ImageField(blank=True, null=True, upload_to='cars/')),
                ('photo4', models.ImageField(blank=True, null=True, upload_to='cars/')),
                ('photo5', models.ImageField(blank=True, null=True, upload_to='cars/')),
            ],
        ),
        migrations.AlterField(
            model_name='car',
            name='photo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='car_photos', to='cars.photo'),
        ),
    ]
