# Generated by Django 5.0.7 on 2024-08-18 03:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0007_photo_alter_car_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='photo',
        ),
        migrations.CreateModel(
            name='CarPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='cars/')),
                ('description', models.CharField(blank=True, max_length=100, null=True)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='car_photo', to='cars.car')),
            ],
        ),
        migrations.DeleteModel(
            name='Photo',
        ),
    ]
